export function Employee(
  empId = 0,
  id = "",
  firstName = "",
  lastName = "",
  email = "",
  phoneNumber1 = "",
  phoneNumber2 = "",
  city = "",
  street = "",
  houseNumber = "",
  zipCode = "",
  password_hash = "",
  role = ""
) {
  this.EmpId = empId;
  this.ID = id;
  this.FirstName = firstName;
  this.LastName = lastName;
  this.Email = email;
  this.PhoneNumber1 = phoneNumber1;
  this.PhoneNumber2 = phoneNumber2;
  this.City = city;
  this.Street = street;
  this.HouseNumber = houseNumber;
  this.ZipCode = zipCode;
  this.Password_hash = password_hash;
  this.Role = role;
}
